### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by danielPerez97** [hohav/peppi#14]
Hey all, I'm starting to fiddle with this library and I believe some more documentation could go a long way. Is there more of it being kept somewhere else outside of GitHub and if not, how can I help to create some "recipes"? Thanks

**Comment by NickCondron** [comment]
You can check the docs page for the crate: https://docs.rs/peppi/1.0.0-alpha.6/peppi/

The slp file spec is here: https://github.com/project-slippi/slippi-wiki/blob/master/SPEC.md

Here is a documentation guide for Rust: https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html

There are some things documented there, but more needs to be added. I don't know what you mean by 'recipes', but if you'd like to help then you should add some documentation and make a pull request. Keep in mind the library APIs are still subject to breaking changes. The author and some users (including me) hang out on the official Slippi Discord, so you can try searching there or asking questions.

A good place to start could be adding the info in the README as documentation so it appears on the docs page for the crate.

**Comment by danielPerez97** [comment]
By recipes I mean specific examples of common use cases that people could look at to get up and running quick. Here's an example from a popular HTTP library on Android:

https://square.github.io/okhttp/recipes/

Perhaps this would be further down the line, but for now I can look into the things you mentioned. Thanks

**Comment by hohav** [comment]
Closing since I think this has been addressed by the README. If you'd like something more, please open a new issue.
