### ISSUE TITLE
Warn user when trying to serialize replay of unsupported version

### ISSUE THREAD

**Issue by NickCondron** [hohav/peppi#45]
Peppi is forward compatible with new replay for deserialization. However it would be impossible to be forward compatible for serialization. We should warn users when they try to serialize a game with a version that is unsupported.

If the user does serialize a replay with an unsupported version, maybe we should modify the version that we write to the file to be the `MAX_SUPPORTED_VERSION` instead of the actual version.

**Comment by hohav** [comment]
I made this a hard error instead for now, because warnings are easy to miss and I don't want losing information to be easy. I might change that if there's demand.
