### ISSUE TITLE
TrackingReader does a poor job reporting where a parse error occurred.

### ISSUE THREAD

**Issue by NickCondron** [hohav/peppi#64]
When a parsed value contains invalid data, an error is returned. However the location that will get reported to the user will be the location after the end of the last read instead of before it.

**Comment by hohav** [comment]
I got rid of TrackingReader because of this, and instead added more logging so we can still find out where an error occurred. Beyond that, I hope to use thiserror's backtrace functionality when it's finally available on stable Rust.
